spring:
  application:
    name: my_project
  profiles: test

server:
  port: 9999

kylin:
  project1:
    userName: admin
    password: KYLIN
    decrypt: true
    connectionUrl: jdbc:kylin://host:7070/project1
  project2:
    userName: admin
    password: KYLIN
    decrypt: true
    connectionUrl: jdbc:kylin://host:7070/project2
