spring:
  application:
    name: my_project
  profiles: test

server:
  port: 9999

kylin:
  weixiaobao:
    userName: admin
    password: KYLIN
    decrypt: true
    connectionUrl: jdbc:kylin://ali-hz-data-platform-7:7070/weixiaobao
  ticauto:
    userName: admin
    password: KYLIN
    decrypt: true
    connectionUrl: jdbc:kylin://ali-hz-data-platform-7:7070/ticauto
